name: SonarCloud Analysis
on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Install dependencies
        run: |
          # RustDesk-specific: Install vcpkg, Flutter, etc., as per repo's build docs
          sudo apt-get update
          sudo apt-get install -y libclang-dev libgtk-3-dev libappindicator3-dev libxdo-dev libayatana-appindicator3-dev
          cargo install cargo-vcpkg
          cargo vcpkg build
          # Add Flutter setup if analyzing Dart code: curl -sSf https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.3-stable.tar.xz | tar xf - -C /opt
          # export PATH="$PATH:/opt/flutter/bin"
          # flutter doctor
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
